{
  "openapi": "3.0.0",
  "info": {
    "title": "UiTPAS API Reference",
    "version": "2.0",
    "contact": {
      "name": "publiq helpdesk",
      "email": "vragen@publiq.be"
    },
    "description": "With UiTPAS API 2.0 you can retrieve ticket sale prices for specific UiTPAS numbers, and register ticket sales for specific UiTPAS numbers.\n\nFuture versions will also include support for more features like saving points and exchanging them for benefits."
  },
  "servers": [
    {
      "url": "https://api.uitpas.be",
      "description": "Production"
    },
    {
      "url": "https://api-test.uitpas.be",
      "description": "Testing"
    }
  ],
  "tags": [
    {
      "name": "TicketSale",
      "description": "Operations related to ticket sales"
    }
  ],
  "paths": {
    "/events/{eventId}/tariffs/{uitpasNumber}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "eventId",
          "in": "path",
          "required": true,
          "description": "UUID of the event for which the ticket is sold"
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "uitpasNumber",
          "in": "path",
          "required": true,
          "description": "UitPAS Number identifying the passholder who wants to buy a ticket"
        }
      ],
      "get": {
        "summary": "Get UiTPAS Tariffs",
        "tags": [
          "TicketSale"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "regularPrice": {
                      "type": "number"
                    },
                    "eventId": {
                      "type": "string"
                    },
                    "uitpasNumber": {
                      "type": "string"
                    },
                    "uitpasTariffs": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "uitpasTariffId": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "tariff": {
                            "type": "number"
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Single tariff example": {
                    "value": {
                      "regularPrice": 10,
                      "eventId": "31e926e2-a35f-11eb-bcbc-0242ac130002",
                      "uitpasNumber": "0230003524312",
                      "uitpasTariffs": [
                        {
                          "uitpasTariffId": "STRUCTURALDISCOUNT",
                          "name": "Kansentarief",
                          "tariff": 1.5
                        }
                      ]
                    }
                  },
                  "Multiple tariffs example": {
                    "value": {
                      "regularPrice": 10,
                      "eventId": "31e926e2-a35f-11eb-bcbc-0242ac130002",
                      "uitpasNumber": "0230003524312",
                      "uitpasTariffs": [
                        {
                          "uitpasTariffId": "STRUCTURALDISCOUNT",
                          "name": "Kansentarief",
                          "tariff": 1.5
                        },
                        {
                          "uitpasTariffId": "COUPON1234",
                          "name": "Cultuurbon 6 euro",
                          "tariff": 4
                        },
                        {
                          "uitpasTariffId": "COUPON2345",
                          "name": "2 euro korting op een specifiek event",
                          "tariff": 8
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-events-eventId-tariffs",
        "description": "Returns the possible UiTPAS discounted **tariffs for an event and a passholder**.\n\nThis UiTPAS tariffs are calculated based on:\n\nThe given `regularPrice` of the ticket.\nThis is the price your user would have to pay for the specific ticket without UiTPAS discount.\n  \nThe `UiTPASnumber` of the passholder.\n  UiTPAS discounts are personal so it's important to identify the passholder to retrieve a list of possible tariffs.\n  \n   The `Event UUID` of the UiTDatabank event\nUiTPAS discounts are limited to specific UiTDatabank events, so it's important to specify the event UUID to retrieve a list of possible tariffs.\n\n\n> **Important**\n> The given regularPrice should be part of the priceInfo array (in one of the price \ncategories) in the UiTdatabank event but can in specific cases differ.\n",
        "security": [
          {
            "Client Access Token (see Authentication docs)": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "number"
            },
            "in": "query",
            "name": "regularPrice",
            "description": "The regular price the passholder would have to pay for the ticket",
            "required": true
          }
        ]
      }
    },
    "/events/{eventId}/ticketSales": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "eventId",
          "in": "path",
          "required": true,
          "description": "UUID of the event for which the TicketSale is registered"
        }
      ],
      "post": {
        "summary": "Register ticket sale(s)",
        "tags": [
          "TicketSale"
        ],
        "operationId": "post-events-eventId-ticketSalesB",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "description": "TicketSaleResponse",
                    "properties": {
                      "ticketSaleRequest": {
                        "type": "object",
                        "description": "TicketSaleRequest",
                        "required": [
                          "uitpasNumber",
                          "uitpasTariffId",
                          "eventId",
                          "regularPrice"
                        ],
                        "properties": {
                          "uitpasNumber": {
                            "type": "string"
                          },
                          "uitpasTariffId": {
                            "type": "string"
                          },
                          "eventId": {
                            "type": "string"
                          },
                          "regularPrice": {
                            "type": "number"
                          }
                        }
                      },
                      "status": {
                        "type": "string",
                        "enum": [
                          "SUCCESS",
                          "INVALID_CARD_STATUS",
                          "INVALID_CARD",
                          "PASSHOLDER_NO_ACTIVE_CARDSYSTEMS",
                          "KANSENSTATUUT_EXPIRED",
                          "MAXIMUM_REACHED"
                        ]
                      },
                      "ticketSale": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "number"
                          }
                        }
                      },
                      "errorMessage": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "ticketSaleRequest",
                      "status"
                    ]
                  }
                },
                "examples": {
                  "Single ticketsale example": {
                    "value": [
                      {
                        "ticketSaleRequest": {
                          "uitpasNumber": "0560002624316",
                          "uitpasTariffId": "COUPON1234",
                          "eventId": "31e926e2-a35f-11eb-bcbc-0242ac130002",
                          "regularPrice": 10
                        },
                        "status": "SUCCESS",
                        "ticketSale": {
                          "id": 1234
                        }
                      }
                    ]
                  },
                  "Multiple ticket sales example": {
                    "value": [
                      {
                        "ticketSaleRequest": {
                          "uitpasNumber": "0560002524314",
                          "uitpasTariffId": "COUPON1234",
                          "eventId": "31e926e2-a35f-11eb-bcbc-0242ac130002",
                          "regularPrice": 10
                        },
                        "status": "SUCCESS",
                        "ticketSale": {
                          "id": 1234
                        }
                      },
                      {
                        "ticketSaleRequest": {
                          "uitpasNumber": "0560002624316",
                          "uitpasTariffId": "COUPON1234",
                          "eventId": "31e926e2-a35f-11eb-bcbc-0242ac130002",
                          "regularPrice": 10
                        },
                        "status": "SUCCESS",
                        "ticketSale": {
                          "id": 1235
                        }
                      }
                    ]
                  },
                  "Example with errors": {
                    "value": [
                      {
                        "ticketSaleRequest": {
                          "uitpasNumber": "0560002524314",
                          "uitpasTariffId": "COUPON1234",
                          "eventId": "31e926e2-a35f-11eb-bcbc-0242ac130002",
                          "regularPrice": 10
                        },
                        "status": "KANSENSTATUUT_EXPIRED",
                        "errorMessage": "De pashouder kan geen ticket kopen. Kansenpas is verlopen."
                      },
                      {
                        "ticketSaleRequest": {
                          "uitpasNumber": "0560002624316",
                          "uitpasTariffId": "COUPON1234",
                          "eventId": "31e926e2-a35f-11eb-bcbc-0242ac130002",
                          "regularPrice": 10
                        },
                        "status": "MAXIMUM_REACHED",
                        "errorMessage": "Er zijn reeds 40 tickets verkocht."
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "description": "Registers one or more new ticket sales with a discounted UiTPAS tariff, so the UiTPAS organiser can get reimbursed for the discount.\n\n> **Important**\n> * Only ticket sales using a discounted UiTPAS tariff (`uitpasTariffId`) can be registered.\n\nA ticketsale is registered using:\n\nThe `uitpasNumber` of the passholder buying the ticket.\n\nThe `eventId` of the UitDatabank event.\n\nThe chosen `uitpasTariffId` from the [Get UiTPAS Tariffs](TODO) request.\n\nThe `regularPrice` the passholder would normally have to pay for this ticket\n\nOptionally `regularPriceLabel` describing the regular price, which can be useful in the financial reporting overview.\n\n\n\n",
        "security": [
          {
            "Client Access Token (see Authentication docs)": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "type": "object",
                  "description": "TicketSaleRequest",
                  "properties": {
                    "uitpasNumber": {
                      "type": "string"
                    },
                    "uitpasTarrifId": {
                      "type": "string"
                    },
                    "eventId": {
                      "type": "string"
                    },
                    "regularPrice": {
                      "type": "number"
                    },
                    "regularPriceLabel": {
                      "type": "string",
                      "description": "Optional description of the regular price. e.g. a price category. Useful for reporting."
                    }
                  },
                  "required": [
                    "uitpasNumber",
                    "uitpasTarrifId",
                    "eventId",
                    "regularPrice"
                  ]
                }
              },
              "examples": {
                "Example without regularPrice": {
                  "value": [
                    {
                      "uitpasNumber": "0560002524314",
                      "uitpasTarrifId": "COUPON1234",
                      "eventId": "31e926e2-a35f-11eb-bcbc-0242ac130002",
                      "regularPrice": 10
                    }
                  ]
                },
                "Example for multiple ticketsales": {
                  "value": [
                    {
                      "uitpasNumber": "0560002524314",
                      "uitpasTarrifId": "COUPON1234",
                      "eventId": "31e926e2-a35f-11eb-bcbc-0242ac130002",
                      "regularPrice": 10
                    },
                    {
                      "uitpasNumber": "0560002624316",
                      "uitpasTarrifId": "COUPON1234",
                      "eventId": "31e926e2-a35f-11eb-bcbc-0242ac130002",
                      "regularPrice": 10
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/events/{eventId}/ticketSales/{ticketSaleId}": {
      "parameters": [
        {
          "$ref": "#/components/parameters/eventId"
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "ticketSaleId",
          "in": "path",
          "required": true,
          "description": "Id of the previously registered ticket sale"
        }
      ],
      "delete": {
        "summary": "Cancel a ticket sale registration",
        "operationId": "delete-events-eventId-ticketSales-ticketSaleId",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Cancels a single ticket sale registration by its id.",
        "tags": [
          "TicketSale"
        ],
        "security": [
          {
            "Client Access Token (see Authentication docs)": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "Client Access Token (see Authentication docs)": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "parameters": {
      "eventId": {
        "name": "eventId",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "format": "uuid"
        },
        "description": "UUID of the event in UiTdatabank"
      },
      "uitpasNumber": {
        "name": "uitpasNumber",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string"
        },
        "description": "Number of the UiTPAS card of the passholder"
      }
    }
  }
}